---
CLEAR_REPORT_FOLDER: true
DISABLE:
  - "HTML"
  - "REPOSITORY"
  - "SPELL"
DISABLE_LINTERS:
  - "CSS_STYLELINT"
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "LICENSE"
FILTER_REGEX_EXCLUDE: "src/api/templates"
FLAVOR_SUGGESTIONS: false
JAVASCRIPT_DEFAULT_STYLE: "prettier"
LINTER_RULES_PATH: ".github/linters"
PRINT_ALPACA: false
TYPESCRIPT_DEFAULT_STYLE: "prettier"
